---
title: "Short Analysis of Lubridillo Site"
format: html
editor: visual
execute:
  warning: false
  message: false
---

# Loading Libraries

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
```

# Documentation

Group:

1\) Created shared folder on Taylor-Adelaide

2\) Created github repository and shared with collaborators-Ale

3)Created Quarto graph with sections to work in separately

Andre - work on graph

# Import, tidy, and join data

```{r}

# read all quebradas
setwd("/courses/EDS214/pr/data/knb_lter_luq_raw")

p_r_m <- read_csv("RioMameyesPuenteRoto.csv", na = c("NA")) %>%
  clean_names() %>%
  mutate(sample_date_ymd = lubridate::ymd(sample_date)) %>%
  mutate(year = year(sample_date_ymd),
         month = month(sample_date_ymd),
         day = day(sample_date_ymd))

b_q_1 <- read_csv("QuebradaCuenca1-Bisley.csv", na = c("NA")) %>%
  clean_names() %>%
  mutate(sample_date_ymd = lubridate::ymd(sample_date)) %>%
  mutate(year = year(sample_date_ymd),
         month = month(sample_date_ymd),
         day = day(sample_date_ymd))

  
b_q_2 <- read_csv("QuebradaCuenca2-Bisley.csv", na = c("NA")) %>%
  clean_names() %>%
  mutate(sample_date_ymd = lubridate::ymd(sample_date)) %>%
  mutate(year = year(sample_date_ymd),
         month = month(sample_date_ymd),
         day = day(sample_date_ymd))

  
b_q_3 <- read_csv("QuebradaCuenca3-Bisley.csv", na = c("NA")) %>%
  clean_names() %>%
  mutate(sample_date_ymd = lubridate::ymd(sample_date)) %>%
  mutate(year = year(sample_date_ymd),
         month = month(sample_date_ymd),
         day = day(sample_date_ymd))
  
# merge data via full join 
stream_water_df <- p_r_m %>% 
  full_join(b_q_1) %>% 
  full_join(b_q_2) %>%
  full_join(b_q_3)

# export the data frame
setwd("/courses/EDS214/pr/data/processed_data")
write_csv(stream_water_df, "stream_water.csv")
```

# Recreate Graph (Step 1)

## WORK UNDER HERE

```{r}

```

## WORK UNDER HERE ALSO

```{r}

```

<https://www.nature.com/articles/s41598-018-33640-3>

https://link.springer.com/article/10.1007/s40996-020-00460-3

```{r}
sediment_ph_df <- stream_water_df %>%
  select(-c(gage_ht, temp, cond, cl, no3_n,
            so4_s, na, k, mg, ca, nh4_n, po4_p,
            tdn, tdp, si_o2, don, dic, doc,
            chloride_code, nitrate_code, 
            sulfate_code, sodium_code, 
            potassium_code, magnesium_code, calcium_code,
            nh4code, po4code, doc_code,
            dic_code, tdn_code, si_o2code,
            don_code)) %>%
  mutate(tss = as.numeric(tss))

sediment_ph_long <- sediment_ph_df %>%
  pivot_longer(cols = c(p_h, tss), names_to = "parameter") %>%
  group_by(year, parameter, sample_id) %>% 
  summarize(mean_parameter = mean(value, na.rm = TRUE)) %>%
  mutate(sample_id = str_replace(sample_id, "MPR", "Puente Roto Mameyes"),
         sample_id = str_replace(sample_id, "Q1", "Quebrada 1 - Bisley"),
         sample_id = str_replace(sample_id, "Q2", "Quebrada 2 - Bisley"),
         sample_id = str_replace(sample_id, "Q3", "Quebrada 3 - Bisley"),
         parameter = str_replace(parameter, "p_h", "PH"),
         parameter = str_replace(parameter, "tss", "Total Suspended Sediment (mg/L)"))
```

```{r}
ggplot(sediment_ph_long,
       aes(x = year,
           y = mean_parameter)) +
  geom_line(aes(color = sample_id)) +
  facet_wrap(~parameter,
             scales = "free",
             ncol = 1) +
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  geom_vline(xintercept = 1989, 
             linetype = "dashed") + 
  geom_vline(xintercept = 2017, 
             linetype = "dashed") + 
  labs(title = "PH and total suspended sediment in stream water \nfrom the Luquillo Mountains",
       caption = "McDowell, W. 2022. Chemistry of stream water \nfrom the Luquillo Mountains ver 4923058. Environmental Data Initiative.\nhttps://doi.org/10.6073/pasta/1dd1a59a7e6fbe95fdf8736477d81b83",
       x = "Year",
       y = NULL)
```
